test(parallel-ci): test how to combine coverage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -211,16 +211,10 @@ jobs:
           name: coverage${{ matrix.group }}
           path: .coverage
 
-  # just for blocking the merge until all parallel core-test are successful
-  success-all-test-coverage:
-    needs: core-test
-    if: always()
+  coverage0:
     runs-on: ubuntu-latest
+    needs: core-test
     steps:
-      - uses: technote-space/workflow-conclusion-action@v2
-      - name: Check Failure
-        if: env.WORKFLOW_CONCLUSION == 'failure'
-        run: exit 1
       - name: Set up Python 3.7
         uses: actions/setup-python@v2
         with:
@@ -235,12 +229,94 @@ jobs:
         run: |
           coverage combine coverage*/.coverage*
           coverage xml
-      - name: Run ls
-        run: ls
-      - name: Upload coverage from test to Codecov
-        uses: codecov/codecov-action@v2
+
+  coverage1:
+    runs-on: ubuntu-latest
+    needs: core-test
+    steps:
+      - name: Set up Python 3.7
+        uses: actions/setup-python@v2
         with:
-          fail_ci_if_error: false
-      - name: Success
-        if: ${{ success() }}
-        run: echo "All Done"
+          python-version: 3.7
+      - name: Prepare environment
+        run: |
+          python -m pip install --upgrade pip
+          pip install pytest-cov
+      - name: Download all coverage artifacts
+        uses: actions/download-artifact@v2
+      - name: Run coverage
+        run: |
+          coverage combine coverage*/.coverage*
+          coverage report
+          coverage xml
+
+  coverage2:
+    runs-on: ubuntu-latest
+    needs: core-test
+    steps:
+      - name: Set up Python 3.7
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.7
+      - name: Prepare environment
+        run: |
+          python -m pip install --upgrade pip
+          pip install pytest-cov
+      - name: Download all coverage artifacts
+        uses: actions/download-artifact@v2
+      - name: Run coverage
+        run: |
+          coverage combine coverage*/.coverage*
+          coverage xml -i
+
+  coverage3:
+    runs-on: ubuntu-latest
+    needs: core-test
+    steps:
+      - name: Set up Python 3.7
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.7
+      - name: Prepare environment
+        run: |
+          python -m pip install --upgrade pip
+          pip install pytest-cov attrs==21.2.0
+      - name: Download all coverage artifacts
+        uses: actions/download-artifact@v2
+      - name: Run coverage
+        run: |
+          coverage combine coverage*/.coverage*
+          coverage xml
+
+#  # just for blocking the merge until all parallel core-test are successful
+#  success-all-test-coverage:
+#    runs-on: ubuntu-latest
+#    needs: core-test
+#    if: always()
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: technote-space/workflow-conclusion-action@v2
+#      - name: Check Failure
+#        if: env.WORKFLOW_CONCLUSION == 'failure'
+#        run: exit 1
+#      - name: Set up Python 3.7
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.7
+#      - name: Prepare environment
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install pytest-cov
+#      - name: Download all coverage artifacts
+#        uses: actions/download-artifact@v2
+#      - name: Run coverage
+#        run: |
+#          coverage combine coverage*/.coverage*
+#          coverage xml
+#      - name: Upload coverage from test to Codecov
+#        uses: codecov/codecov-action@v2
+#        with:
+#          fail_ci_if_error: false
+#      - name: Success
+#        if: ${{ success() }}
+#        run: echo "All Done"
